CREATE TABLE IF NOT EXISTS cart(
com_id INT AUTO_INCREMENT,
user_name VARCHAR(255) NOT NULL,
movie_name VARCHAR(255) NOT NULL,
director VARCHAR (255) NOT NULL,
description VARCHAR(500) NOT NULL,
price VARCHAR(255) NOT NULL,
genre VARCHAR(255) NOT NULL,
photo VARCHAR (255) NOT NULL,
PRIMARY KEY(com_id)
);